users:
  standard:
    username: standard_user
    password: secret_sauce

  locked:
    username: locked_out_user
    password: secret_sauce

Validation_data:
  Tc1: Logo not visible -> Login failed
  Tc2: Sorry, this user has been banned
  Tc3: https://www.saucedemo.com/